
name: erca
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.5
  - proplot=0.6.4
  - matplotlib=3.2.0
  - cartopy=0.17.0
  - intake-esm=2020.6.11
  - xesmf=0.3.0
  - isort
  - esmpy=8.0.1
  - black
  - nbresuse
  - nodejs[version='>=10.0']
  - python-graphviz
  - dask
  - nb_conda_kernels
  - netcdf4
  - jupyterlab_code_formatter
  - jupyterlab
  - jupyter
  - gcsfs
  - zarr

